### ISSUE TITLE
 Error loading model /tmp/fasttext-langdetect/lid.176.ftz: vector::_M_default_append

### ISSUE THREAD

**Issue by wildwind0** [LlmKira/fast-langdetect#4]
when using `from fast_langdetect import detect`,  I encountered an error.
![image](https://github.com/user-attachments/assets/2df2d611-fc3f-4db1-92e4-2a984f82f0c1)

**Comment by sudoskys** [comment]
try `rm /tmp/fasttext-langdetect/lid.176.ftz`

**Comment by sudoskys** [comment]
link to https://github.com/opendatalab/MinerU/issues/266

**Comment by sudoskys** [comment]
resolving
